#!/usr/bin/env python3
"""paper_tables.py — export the paper's tables from the deposited workbook, and check the paper against them.

InferenceCarbon framework v1.0.0. The workbook (data/workbooks/OpenAIModelCalculations_v1.0.0.xlsx) is the
paper-authoritative calculation chain: Assumptions -> Grid Intensity Data (Tables 3, 4, 5, 10) -> Table 6 -> Table 7 ->
C_Low / C_High -> Table 8, with the corpus-derived inputs on the Corpus / Bootstrap / Ratio Envelopes sheets
(regenerated by corpus_summary.py) and the shape correction of Appendix D.5.8 on Shape Correction.

  python paper_tables.py --workbook ../data/workbooks/OpenAIModelCalculations_v1.0.0.xlsx --out out/
  diff -r out/ expected/                              # replicator's check against the committed outputs
  python paper_tables.py --workbook ... --paper InferenceCarbon_v1.0.0.docx   # cell-by-cell check of the paper

The export reads the workbook's cached values. If any are missing (a workbook saved without recalculation),
recalculate first:  soffice --headless --convert-to xlsx --outdir recalc/ <workbook>
No API key and no corpus download are needed; runtime is a few seconds.
"""
import argparse, csv, os, re, sys, zipfile
import openpyxl

SHEETS = {  # sheet -> (output file, header row, first data row, last column)
    'Grid Intensity Data': ('tables_3_4_5_10.csv', None, None, 7),
    'Table 6': ('table_6.csv', 2, 3, 12), 'Table 7': ('table_7.csv', 2, 3, 7), 'Table 8': ('table_8.csv', 2, 3, 10),
    'C_Low': ('table_c1_low.csv', 2, 3, 12), 'C_High': ('table_c2_high.csv', 2, 3, 12),
    'Table B1': ('table_b1.csv', 2, 3, 4), 'Table 1': ('table_1.csv', 2, 3, 10),
    'Ratio Envelopes': ('table_c3.csv', 2, 3, 15), 'Shape Correction': ('shape_correction.csv', None, None, 7),
    'Table 8 - Log Widths': ('levers_log_spans.csv', None, None, 12), 'Pinching': ('table_11.csv', None, None, 12),
}
TABLE9 = [  # Table 9 rows: (use case, variant, output tokens, shape factor S from 'Shape Correction'!E17 or 1)
    ('Simple Q&A, short generation', 'gpt-5.6-luna (low)', 300, None),
    ('Drafting, summarization', 'gpt-5.6-terra (low)', 1000, None),
    ('Light reasoning (explain, plan)', 'gpt-5.6-terra (medium)', 1000, None),
    ('Heavy reasoning, agentic work', 'gpt-5.6-sol (high)', 2000, None),
    ('Long-context analysis and reporting', 'gpt-5.6-sol (high)', 10000, None),
    ('Long-context retrieval or agentic turn (50,000 in)', 'gpt-5.6-sol (high)', 1000, 'E17'),
]

def val(ws, r, c):
    """Cell value for export. Every non-boolean number is written as a float rounded to 6 dp, so a
    workbook recalculated by LibreOffice (which stores integer-valued results as integers) exports
    byte-identically to one saved by Excel (which stores them as floats): 411 and 411.0 both become 411.0."""
    v = ws.cell(r, c).value
    if isinstance(v, bool): return v
    return round(float(v), 6) if isinstance(v, (int, float)) else v

def export(wb, out):
    os.makedirs(out, exist_ok=True); missing = 0
    for name, (fn, hdr, first, last) in SHEETS.items():
        if name not in wb.sheetnames: print('  (no sheet', name + ')'); continue
        ws = wb[name]
        with open(os.path.join(out, fn), 'w', newline='') as f:
            w = csv.writer(f)
            for r in range(1, ws.max_row + 1):
                row = [val(ws, r, c) for c in range(1, last + 1)]
                if any(x is not None for x in row): w.writerow(row)
                for c in range(1, last + 1):
                    cell = ws.cell(r, c)
                    if cell.data_type == 'f' or (cell.value is None and isinstance(cell.value, str) and cell.value.startswith('=')): missing += 1
    # Table 9 (user decision layer) from Table 8 and Shape Correction
    t9 = wb['Table 8']; rows = {t9.cell(r, 1).value: [t9.cell(r, c).value for c in range(2, 8)] for r in range(3, 60) if t9.cell(r, 1).value}
    S = wb['Shape Correction']['E17'].value if 'Shape Correction' in wb.sheetnames else 1.0
    with open(os.path.join(out, 'table_9.csv'), 'w', newline='') as f:
        w = csv.writer(f); w.writerow(['use_case', 'variant', 'output_tokens', 'shape_factor', 'lb_low', 'lb_central', 'lb_high', 'mb_low', 'mb_central', 'mb_high'])
        for uc, var, tok, s in TABLE9:
            k = tok / 1000 * (S if s else 1.0); v = rows[var]
            w.writerow([uc, var, tok, round(S if s else 1.0, 4)] + [round(x * k, 2) for x in v])
    print('exported to', out)

# ---------------- paper check ----------------
W = 'http://schemas.openxmlformats.org/wordprocessingml/2006/main'
def docx_tables(path):
    from lxml import etree
    root = etree.fromstring(zipfile.ZipFile(path).read('word/document.xml'))
    ns = {'w': W}
    def txt(e):
        return ''.join(t.text or '' for t in e.iter('{%s}t' % W) if not any(a.tag == '{%s}del' % W for a in t.iterancestors()))
    out = []
    for tb in root.iter('{%s}tbl' % W):
        out.append([[re.sub(r'\s+', ' ', txt(tc)).strip() for tc in tr.findall('w:tc', ns)] for tr in tb.findall('w:tr', ns)])
    return out

def num(s):
    m = re.match(r'^[~≈]?\s*(-?[\d,]*\.?\d+)', s or '')
    return float(m.group(1).replace(',', '')) if m else None

def check(wb, paper):
    tabs = docx_tables(paper)
    def find(header_words):
        for i, t in enumerate(tabs):
            h = ' '.join(t[0] + (t[1] if len(t) > 1 else []))
            if all(wd in h for wd in header_words): return i
    key = lambda s: re.sub(r'[\s*]', '', s.lower())
    report = []
    def compare(tname, sheet, docx_cols, sheet_cols, skip_rows=1, dp=2, dps=None):
        i = find(tname); ws = wb[sheet]
        if i is None: report.append((tname, 'table not found')); return
        wbrows = {key(ws.cell(r, 1).value): [ws.cell(r, c).value for c in sheet_cols] for r in range(3, 80) if ws.cell(r, 1).value}
        ok = bad = 0
        for row in tabs[i][skip_rows:]:
            k = key(row[0]) if row else ''
            if k not in wbrows: continue
            for j, (dc, wv) in enumerate(zip(docx_cols, wbrows[k])):
                dp = dps[j] if dps else dp
                pv = num(row[dc]) if dc < len(row) else None
                if pv is None or wv is None or isinstance(wv, str): continue
                if abs(pv - round(float(wv), dp)) <= 0.5 * 10 ** -dp + 1e-9: ok += 1
                else: bad += 1; report.append((tname, row[0], dc, pv, round(float(wv), dp)))
        report.append((tname, f'{ok} agree, {bad} differ'))
    compare(['Anchor', 'Tokens-Per-'], 'Table 6', [2, 3, 4, 6, 8, 10, 11], [3, 4, 5, 7, 9, 11, 12], dps=[1, 3, 2, 2, 2, 2, 2])
    compare(['Adjusted', 'Market-Based gCO2e / 1,000'], 'Table 7', [1, 2, 3, 4, 5], [2, 3, 4, 5, 6], dp=2)
    compare(['Location-Based gCO2e / 1,000', 'procurement'], 'Table 8', [1, 2, 3, 4, 5, 6, 7, 8, 9], [2, 3, 4, 5, 6, 7, 8, 9, 10], skip_rows=2, dp=2)
    compare(['Fixed_low', 'T_low'], 'C_Low', [1, 3, 4, 5, 6, 7, 8, 9, 10], [2, 6, 7, 8, 9, 10, 11, 12, 13], dp=2)
    compare(['Fixed_high', 'T_high'], 'C_High', [1, 3, 4, 5, 6, 7, 8, 9, 10], [2, 6, 7, 8, 9, 10, 11, 12, 13], dp=2)
    compare(['Mean visible TPS'], 'Table B1', [1, 2, 3], [2, 3, 4], dp=1)
    for r in report:
        print(' ', *r)

if __name__ == '__main__':
    ap = argparse.ArgumentParser(); ap.add_argument('--workbook', required=True); ap.add_argument('--out', default='out')
    ap.add_argument('--paper'); a = ap.parse_args()
    wb = openpyxl.load_workbook(a.workbook, data_only=True)
    if wb['Table 7']['E3'].value is None:
        sys.exit('workbook has no cached values — recalculate it first (see docstring)')
    export(wb, a.out)
    if a.paper: check(wb, a.paper)
